//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClienteMTIS.Empleado {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EmpleadoSOAP", Namespace="http://www.mtis.org/Empleado/")]
    public partial class Empleado : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback nuevoOperationCompleted;
        
        private System.Threading.SendOrPostCallback borrarOperationCompleted;
        
        private System.Threading.SendOrPostCallback modificarOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Empleado() {
            this.Url = global::ClienteMTIS.Properties.Settings.Default.ClienteMTIS_localhost_Empleado;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event nuevoCompletedEventHandler nuevoCompleted;
        
        /// <remarks/>
        public event borrarCompletedEventHandler borrarCompleted;
        
        /// <remarks/>
        public event modificarCompletedEventHandler modificarCompleted;
        
        /// <remarks/>
        public event consultarCompletedEventHandler consultarCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mtis.org/Empleado/nuevo", RequestNamespace="http://www.mtis.org/Empleado/", ResponseNamespace="http://www.mtis.org/Empleado/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("allOK", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool nuevo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string DNI, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nombre, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string apellidos, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string direccion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string poblacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string telefono, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string email, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")] System.DateTime nacimiento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string NSS, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string IBAN, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string SoapKey, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string errors) {
            object[] results = this.Invoke("nuevo", new object[] {
                        DNI,
                        nombre,
                        apellidos,
                        direccion,
                        poblacion,
                        telefono,
                        email,
                        nacimiento,
                        NSS,
                        IBAN,
                        SoapKey});
            errors = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void nuevoAsync(string DNI, string nombre, string apellidos, string direccion, string poblacion, string telefono, string email, System.DateTime nacimiento, string NSS, string IBAN, string SoapKey) {
            this.nuevoAsync(DNI, nombre, apellidos, direccion, poblacion, telefono, email, nacimiento, NSS, IBAN, SoapKey, null);
        }
        
        /// <remarks/>
        public void nuevoAsync(string DNI, string nombre, string apellidos, string direccion, string poblacion, string telefono, string email, System.DateTime nacimiento, string NSS, string IBAN, string SoapKey, object userState) {
            if ((this.nuevoOperationCompleted == null)) {
                this.nuevoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnuevoOperationCompleted);
            }
            this.InvokeAsync("nuevo", new object[] {
                        DNI,
                        nombre,
                        apellidos,
                        direccion,
                        poblacion,
                        telefono,
                        email,
                        nacimiento,
                        NSS,
                        IBAN,
                        SoapKey}, this.nuevoOperationCompleted, userState);
        }
        
        private void OnnuevoOperationCompleted(object arg) {
            if ((this.nuevoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nuevoCompleted(this, new nuevoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mtis.org/Empleado/borrar", RequestNamespace="http://www.mtis.org/Empleado/", ResponseNamespace="http://www.mtis.org/Empleado/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("allOK", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool borrar([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string DNI, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string SoapKey, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string errors) {
            object[] results = this.Invoke("borrar", new object[] {
                        DNI,
                        SoapKey});
            errors = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void borrarAsync(string DNI, string SoapKey) {
            this.borrarAsync(DNI, SoapKey, null);
        }
        
        /// <remarks/>
        public void borrarAsync(string DNI, string SoapKey, object userState) {
            if ((this.borrarOperationCompleted == null)) {
                this.borrarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnborrarOperationCompleted);
            }
            this.InvokeAsync("borrar", new object[] {
                        DNI,
                        SoapKey}, this.borrarOperationCompleted, userState);
        }
        
        private void OnborrarOperationCompleted(object arg) {
            if ((this.borrarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.borrarCompleted(this, new borrarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mtis.org/Empleado/modificar", RequestNamespace="http://www.mtis.org/Empleado/", ResponseNamespace="http://www.mtis.org/Empleado/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("allOK", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool modificar([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string DNI, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string SoapKey, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nombre, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string apellidos, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string direccion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string poblacon, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")] System.DateTime nacimiento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string telefono, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string email, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string NSS, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string IBAN, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string errors) {
            object[] results = this.Invoke("modificar", new object[] {
                        DNI,
                        SoapKey,
                        nombre,
                        apellidos,
                        direccion,
                        poblacon,
                        nacimiento,
                        telefono,
                        email,
                        NSS,
                        IBAN});
            errors = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void modificarAsync(string DNI, string SoapKey, string nombre, string apellidos, string direccion, string poblacon, System.DateTime nacimiento, string telefono, string email, string NSS, string IBAN) {
            this.modificarAsync(DNI, SoapKey, nombre, apellidos, direccion, poblacon, nacimiento, telefono, email, NSS, IBAN, null);
        }
        
        /// <remarks/>
        public void modificarAsync(string DNI, string SoapKey, string nombre, string apellidos, string direccion, string poblacon, System.DateTime nacimiento, string telefono, string email, string NSS, string IBAN, object userState) {
            if ((this.modificarOperationCompleted == null)) {
                this.modificarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmodificarOperationCompleted);
            }
            this.InvokeAsync("modificar", new object[] {
                        DNI,
                        SoapKey,
                        nombre,
                        apellidos,
                        direccion,
                        poblacon,
                        nacimiento,
                        telefono,
                        email,
                        NSS,
                        IBAN}, this.modificarOperationCompleted, userState);
        }
        
        private void OnmodificarOperationCompleted(object arg) {
            if ((this.modificarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.modificarCompleted(this, new modificarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mtis.org/Empleado/consultar", RequestNamespace="http://www.mtis.org/Empleado/", ResponseNamespace="http://www.mtis.org/Empleado/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("allOK", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool consultar([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ref string DNI, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string SoapKey, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string nombre, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string apellidos, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string direccion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string poblacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string telefono, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string email, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")] out System.DateTime nacimiento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string NSS, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string IBAN, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string errors) {
            object[] results = this.Invoke("consultar", new object[] {
                        DNI,
                        SoapKey});
            DNI = ((string)(results[1]));
            nombre = ((string)(results[2]));
            apellidos = ((string)(results[3]));
            direccion = ((string)(results[4]));
            poblacion = ((string)(results[5]));
            telefono = ((string)(results[6]));
            email = ((string)(results[7]));
            nacimiento = ((System.DateTime)(results[8]));
            NSS = ((string)(results[9]));
            IBAN = ((string)(results[10]));
            errors = ((string)(results[11]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void consultarAsync(string DNI, string SoapKey) {
            this.consultarAsync(DNI, SoapKey, null);
        }
        
        /// <remarks/>
        public void consultarAsync(string DNI, string SoapKey, object userState) {
            if ((this.consultarOperationCompleted == null)) {
                this.consultarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarOperationCompleted);
            }
            this.InvokeAsync("consultar", new object[] {
                        DNI,
                        SoapKey}, this.consultarOperationCompleted, userState);
        }
        
        private void OnconsultarOperationCompleted(object arg) {
            if ((this.consultarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarCompleted(this, new consultarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void nuevoCompletedEventHandler(object sender, nuevoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nuevoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nuevoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void borrarCompletedEventHandler(object sender, borrarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class borrarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal borrarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void modificarCompletedEventHandler(object sender, modificarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class modificarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal modificarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void consultarCompletedEventHandler(object sender, consultarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string DNI {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string nombre {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string apellidos {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string direccion {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string poblacion {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
        
        /// <remarks/>
        public string telefono {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[6]));
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[7]));
            }
        }
        
        /// <remarks/>
        public System.DateTime nacimiento {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[8]));
            }
        }
        
        /// <remarks/>
        public string NSS {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[9]));
            }
        }
        
        /// <remarks/>
        public string IBAN {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[10]));
            }
        }
        
        /// <remarks/>
        public string errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[11]));
            }
        }
    }
}

#pragma warning restore 1591