// Template: Base Controller (ApiControllerBase.t4) version 5.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using ServidorRAML.Empleado.Models;

// Do not modify this file. This code was generated by AMF Server Scaffolder

namespace ServidorRAML.Empleado
{
    [RoutePrefix("empleados")]
    public partial class EmpleadosController : ApiController
    {


/// <summary>
		/// Crear un empleado - /empleados/nuevo
		/// </summary>
		/// <param name="empleado">Objeto empleado para almacenar los datos de un empleado.</param>
		/// <param name="restkey">Una restkey valida almacenada en la bdd (Concede permisos para realizar al operacion)</param>
		/// <returns>MultipleEmpleadosNuevoPost</returns>
        [ResponseType(typeof(MultipleEmpleadosNuevoPost))]
        [HttpPost]
        [Route("nuevo")]
        public virtual IHttpActionResult PostBase([FromBody] ServidorRAML.Empleado.Models.Empleado empleado,[FromUri] string restkey)
        {
            // Do not modify this code
                        return  ((IEmpleadosController)this).Post(empleado,restkey);
                    }

/// <summary>
		/// Obtener un empleado a partir de su DNI y una RestKey - /empleados/consultar
		/// </summary>
		/// <param name="restkey">Una restkey valida almacenada en la bdd (Concede permisos para realizar al operacion)</param>
		/// <param name="dni">DNI del empleado a consultar.</param>
		/// <returns>MultipleEmpleadosConsultarGet</returns>
        [ResponseType(typeof(MultipleEmpleadosConsultarGet))]
        [HttpGet]
        [Route("consultar")]
        public virtual IHttpActionResult GetBase([FromUri] string restkey,[FromUri] string dni)
        {
            // Do not modify this code
                        return  ((IEmpleadosController)this).Get(restkey,dni);
                    }

/// <summary>
		/// Actualiza los datos de un empleado tras validar una RestKey - /empleados/modificar
		/// </summary>
		/// <param name="empleado">Objeto empleado para almacenar los datos de un empleado.</param>
		/// <param name="restkey">Una restkey valida almacenada en la bdd (Concede permisos para realizar al operacion)</param>
		/// <returns>MultipleEmpleadosModificarPut</returns>
        [ResponseType(typeof(MultipleEmpleadosModificarPut))]
        [HttpPut]
        [Route("modificar")]
        public virtual IHttpActionResult PutBase([FromBody] ServidorRAML.Empleado.Models.Empleado empleado,[FromUri] string restkey)
        {
            // Do not modify this code
                        return  ((IEmpleadosController)this).Put(empleado,restkey);
                    }

/// <summary>
		/// Eliminar un empleado de la base de datos - /empleados/borrar
		/// </summary>
		/// <param name="restkey">Una restkey valida almacenada en la bdd (Concede permisos para realizar al operacion)</param>
		/// <param name="dni">DNI del empleado a consultar.</param>
		/// <returns>MultipleEmpleadosBorrarDelete</returns>
        [ResponseType(typeof(MultipleEmpleadosBorrarDelete))]
        [HttpDelete]
        [Route("borrar")]
        public virtual IHttpActionResult DeleteBase([FromUri] string restkey,[FromUri] string dni)
        {
            // Do not modify this code
                        return  ((IEmpleadosController)this).Delete(restkey,dni);
                    }
    }
}
