// Template: Models (ApiModel.t4) version 5.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ServidorRAML.Empleado.Models
{
    /// <summary>
    /// Objeto empleado para almacenar los datos de un empleado.
    /// </summary>
    public partial class Empleado
    {
        

        [Required]
        [MaxLength(9)]
        [MinLength(9)]
        public string DNI { get; set; }

        [MaxLength(64)]
        [MinLength(0)]
		[JsonProperty("Nombre?")]
        public string Nombre { get; set; }

        [MaxLength(64)]
        [MinLength(0)]
		[JsonProperty("Apellidos?")]
        public string Apellidos { get; set; }

        [MaxLength(256)]
        [MinLength(0)]
		[JsonProperty("Direccion?")]
        public string Direccion { get; set; }

        [MaxLength(32)]
        [MinLength(0)]
		[JsonProperty("Poblacion?")]
        public string Poblacion { get; set; }

        [MaxLength(16)]
        [MinLength(0)]
		[JsonProperty("Telefono?")]
        public string Telefono { get; set; }

        [MaxLength(128)]
        [MinLength(0)]
		[JsonProperty("Email?")]
        public string Email { get; set; }

        [MaxLength(16)]
        [MinLength(0)]
        public string Nacimiento { get; set; }

        [MaxLength(12)]
        [MinLength(0)]
		[JsonProperty("NSS?")]
        public string NSS { get; set; }

        [MaxLength(24)]
        [MinLength(0)]
		[JsonProperty("IBAN?")]
        public string IBAN { get; set; }
    } // end class

} // end Models namespace

