// Template: Models (ApiModel.t4) version 5.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ServidorRAML.Utilidades.Models
{
    /// <summary>
    /// Objeto utilziado para transmitir un mensaje y codigo en caso de algun error.
    /// </summary>
    public partial class Error
    {
        

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
		[JsonProperty("code")]
        public int Code { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
		[JsonProperty("message")]
        public string Message { get; set; }
    } // end class

} // end Models namespace

