// Template: Models (ApiModel.t4) version 5.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using ServidorRAML.Utilidades.Models;

namespace ServidorRAML.Seguridad.Models
{
    /// <summary>
    /// Multiple Response Types Ipstring, Error
    /// </summary>
    public partial class MultipleSeguridadObtenerNivelesGet
    {
        

        /// <summary>
        /// Lista de salas obtenida 
        /// </summary>

        public IList<string> Ipstring { get; set; }

        /// <summary>
        /// Ha ocurrido algún error durante la consulta. Objeto utilziado para transmitir un mensaje y codigo en caso de algun error.
        /// </summary>

        public Error Error { get; set; }
    } // end class

} // end Models namespace

