// Template: Models (ApiModel.t4) version 5.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ServidorRAML.Utilidades.Models
{
    /// <summary>
    /// Multiple Response Types Ipbool, Error
    /// </summary>
    public partial class MultipleUtilidadesValidarNIFGet
    {
        

        /// <summary>
        /// El DNI es valido 
        /// </summary>

        public bool? Ipbool { get; set; }

        /// <summary>
        /// El DNI o restkey no validos Objeto utilziado para transmitir un mensaje y codigo en caso de algun error.
        /// </summary>

        public Error Error { get; set; }
    } // end class

} // end Models namespace

