// Template: Models (ApiModel.t4) version 5.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using ServidorRAML.Utilidades.Models;

namespace ServidorRAML.Empleado.Models
{
    /// <summary>
    /// Multiple Response Types Empleado, Error
    /// </summary>
    public partial class MultipleEmpleadosConsultarGet
    {
        

        /// <summary>
        /// Empleado consultado correctamente. Objeto empleado para almacenar los datos de un empleado.
        /// </summary>

        public Empleado Empleado { get; set; }

        /// <summary>
        /// Ha ocurrido un error al crear el empleado. Objeto utilziado para transmitir un mensaje y codigo en caso de algun error.
        /// </summary>

        public Error Error { get; set; }
    } // end class

} // end Models namespace

