// Template: Models (ApiModel.t4) version 5.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ServidorRAML.Seguridad.Models
{
    /// <summary>
    /// Objeto seguridad para el acceso a la gestion de la &apos;empresa&apos;.
    /// </summary>
    public partial class Seguridad
    {
        

        [Required]
        [MaxLength(9)]
        [MinLength(9)]
        public string DNI { get; set; }

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
        public string Sala { get; set; }
    } // end class

} // end Models namespace

